imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    session:
        cookie_lifetime: 900

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    cache: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.jar

services:
    #para saber que usuario se conecta y se desconecta
    authentication_handler:
        class: mio\mioBundle\AuthenticationHandler
        arguments: [@router , @doctrine.orm.entity_manager, @security.context]
    #para ver los cambios en las entidades
    listenercrud:
        class: mio\mioBundle\ListenerCrud
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: onFlush}
    #para personalizar la pagina de accesso denegado
    accessdenied_handler:
        class: mio\mioBundle\AccessDeniedHandler
        arguments: [@router , @security.context ]
        tags:
           - { name: kernel.event_listener, event: security.kernel_response, method: handle}
    #para personalizar la pagina de ruta no encontrada
    #listenerexepcion:
    #   class: mio\mioBundle\ListenerExcepcion
    #   arguments: [@router]
    #   tags:
    #      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    listenerparalogout:
        class: mio\mioBundle\RequestListener
        arguments: [@router, @security.context]
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    mio_locale.locale_listener:
        class: mio\mioBundle\ListenerLocale
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }